name: mdet-lsst-sims
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - ipykernel
  - jupyter
  - stackvana
  - meds
  - lsstdesc.weaklensingdeblending
  - ngmix
  - galsim
  - wget
  - pip:
    - git+https://github.com/LSSTDESC/descwl-shear-sims.git
